android/src/main/java/com/brentvatne/react/ReactVideoView.java, ios/Video/RCTVideo.m
Calculate seekable start and return it on progress update.
=> Live seekable ranges start

ios/Video/RCTVideo.m, react-native-video.podspec
=> added download playback support

ios/Video/RCTVideo.m
commented out code in loadingRequestHandling in order to fix airplay
=> airplay fix

ios/RCTVideo-Bridging-Header.h, ios/RCTVideo.xcodeproj/project.pbxproj, ios/Video/RCTVideo.h, ios/Video/RCTVideo.m, ios/Video/RCTVideoManager.m, react-native-video.podspec
integration with youbora plugin
=> integration with youbora plugin

android-exoplayer/build.gradle, android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java, android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerViewManager.java
Youbora plugin integration in android.
=> feat: SAAA-5875 Add youbora plugin for android

android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
Change option names as per the change.
=> fix: SAAA-5875 Change option names

android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
Support to push offline events
=> feat: Push offline events android

ios/Video/RCTVideo.m
=> send offline events when app goes online in ios

android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
=> update decoder fallback

android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
=> Add decoder fall back

android-exoplayer/build.gradle, android-exoplayer/src/main/java/com/brentvatne/exoplayer/LicencesDataStore.java, android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java, android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerViewManager.java
=> Channel performance

android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java, android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerViewManager.java
=> feat: made licence persisting disabled by default

android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java, android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerViewManager.java
https://skynz.atlassian.net/browse/SAAA-10599
=> SAAA-10599 added licenseMultiSession support

android-exoplayer/src/main/java/com/brentvatne/exoplayer/ExoPlayerView.java
I aligned the subtitle position with the fixed position in the Figma design, rather than relying on the position determined by the text track file.
=> fix: [SAAA-10678] fix subtitle position

Video.js, android-exoplayer/src/main/java/com/brentvatne/exoplayer/ExoPlayerView.java, android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java, android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerViewManager.java
https://skynz.atlassian.net/browse/SAAA-10906
=> SAAA-10906 Single Player Instance

android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
https://github.com/react-native-video/react-native-video/pull/2670
fix maxbitrate property being ignored on Android
=> fix maxbitrate property being ignored on Android

android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java, android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerViewManager.java
PR for implement FF/RW by native Android code
=> Feat: add fast forward rewind

android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
add condition check for `progressHandler`.
=> Fix progress update interval

android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java, android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerViewManager.java
https://github.com/react-native-video/react-native-video/pull/2871/files
=> Feat: make focusable optional for android

android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
added a logic to restart the player when MediaCodecVideoRenderer error
=> SAAA-11537 MediaCodecVideoRenderer error handling 

android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
initialise Exoplayer only if the player is null
=> SAAA-11515 check if player is null

android/src/main/java/com/brentvatne/exoplayer/ExoPlayerView.java, android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java, android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerViewManager.java
=> clear subtitle when the src changes

android/src/main/java/com/brentvatne/exoplayer/DataSourceUtil.java
=> remove duplicated User-Agent API header - If user-agent API header provided by client default user-agent will be removed

ios/Video/Features/RCTVideoUtils.swift, ios/Video/RCTVideo.swift
https://skynz.atlassian.net/browse/SAAA-12459
this code was taken as a base:
https://github.com/react-native-video/react-native-video/compare/master...skytvnz:react-native-video:master-mobile-old
=> SAAA-12459 Migrate Obj C code to Swift

android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
Youbora now works without duplicate events for LIVE TV. Pending scenarios
1) First load of LIVE TV we still see skewed behaviour
2) When parental pin pops up then the event stops and doesnt start again till we change channel
The above needs more investigation
=> fix: SAAA-12442 youbora fixes for LIVE TV

ios/Video/RCTVideo.swift
Updated to recommended way
https://github.com/NPAW/avplayer-adapter-ios?tab=readme-ov-file#swift-1
=> Youbora iOS fix

android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
=> SAAA-12594 fix set youbora only when analytic meta update

android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
=> SAAA-12594 add fix for wfs

android/build.gradle, android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
=> added download playback support for Android.

android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
=> Saaa-12442 youbora catch error

android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java, android/src/main/java/com/brentvatne/exoplayer/VideoEventEmitter.java
=> SAAA-12693-alternate-audio-support-for-ip-streams

android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java, ios/Video/RCTVideo.swift
=> SAAA-12548 update mobile youbora

android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
=> SAAA-12548 add on error

ios/Video/RCTVideo.swift
=> SAAA-12548 add ios change

ios/Video/RCTVideo.swift
=> SAAA-12358 fix ios player init duplicate

android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
Update the documentation
Update the changelog
Provide an example of how to test the change
Focus the PR on only one area
Testing multiple features takes longer …
=> SAAA-13072-pod-crash-with-soak-test-script

ios/Video/Features/RCTPlayerOperations.swift
https://skynz.atlassian.net/issues/SAAA-13118
Testing multiple features takes longer than isolated changes and if there is a bug in one feature, prevents the other …
=> fix: SAAA-13118 - Sound comes out of the iOS devices instead of Airpods or any Audio devices when connected via SkyGO App

react-native-video.podspec
…
Testing multiple features takes longer than isolated changes and if there is a bug in one feature, prevents the other parts of your PR from getting merged until …
=> fix: SAAA-13050 - Downloading speed is very slow and is taking a longer time to download content

react-native-video.podspec
=> fix :  Reverting 4.2.5 minimum version set.

ios/Video/RCTVideo.swift
=> fix(ios): fix pip memory leak

ios/Video/DataStructures/SubtitleStyle.swift, ios/Video/Features/RCTPlayerObserver.swift, ios/Video/RCTVideo.swift, ios/Video/RCTVideoManager.m
Added Subtitle Toggle support for HLS streams in iOS devices, The changes are as suggested by library and are available in 6.0.0 version. 
Added additional changes are required 
https://github.com/TheWidlarzGroup/react-native-video/pull/3583
https://github.com/user-attachments/assets/47593a7f-3236-413c-8eca-d1e0fc97afa2
=> feat: SAAA-13569 - SkyGO - Subtitle Toggle support for HLS stream ( Live playback ) in IOS

Video.js
=> fix: SAAA-14015 - App is crashing when we navigate from Watch TV to any of the Tabs

android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java, android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerViewManager.java
=> feat: SAAA-13799-remove-licence-proxy-props
